---
- name: deploy bazarr
  hosts: all
  become: yes
  tasks:

  - name: create volume
    community.docker.docker_volume:
      name: bazarr-data
      driver: local

  - name: deploy bazarr
    community.docker.docker_container:
      name: bazarr
      image: "lscr.io/linuxserver/bazarr:latest"
      env:
       PUID=1000
       GUID=1000
      ports:
        - "6767:6767"
      volumes:
        - /htpc/Media/Movies:/movies
        - /htpc/Media/TV-Shows;/tv
        - /home/callum/docker/bazarr/config:/config
      restart_policy: unless-stopped
