---
- name: deploy plex
  hosts: all
  become: yes
  tasks:

  - name: create new volume
    community.docker.docker_volume:
      name: plex-data

  - name: deploy plex
    community.docker.docker_container:
      name: plex
      image: "lscr.io/linuxserver/plex:latest"
      network_mode: host
      env:
        PUID=1000
        PGID=1000
        VERSION=docker
      volumes:
        - plex-data:/config
        - /htpc/Media/TV-Shows:/tv
        - /htpc/Media/Movies:/movies
      restart_policy: unless-stopped
