---
- name: deploy portainer-ce latest
  hosts: all
  become: yes
  tasks:
  - name: create new volume
    community.docker.docker_volume:
      name: portainer-data
  - name: deploy portainer
    community.docker.docker_container:
      name: portainer
      image: "docker.io/portainer/portainer-ce"
      ports:
        - "9000:9000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer-data:/data
      restart_policy: unless-stopped
