---
- name: deploy sonarr
  hosts: all
  become: yes
  tasks:

  - name: create volume
    community.docker.docker_volume:
      name: sonarr-data
      driver: local

  - name: deploy sonarr
    community.docker.docker_container:
      name: sonarr
      image: "lscr.io/linuxserver/sonarr:latest"
      env:
        PUID=1000
        GUID=1000
      ports:
        - "8989:8989"
      volumes:
        - /home/callum/docker/sonarr/config:/config
        - /htpc/Media/TV-Shows:/tv
        - /htpc/Media/Downloads:/downloads
      restart_policy: unless-stopped
